Repository TerraFirmaGreg-Team/Modpack-Modern, pull requests merged in 2025-04, with the labels that each got.

#820 GT light/dark concrete recipe fix
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Bug

#815 add recipes for passthrough hatches
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#803 Fix Chocolate Dust Recipe, Add Additional Chocolate Dust/Powder Recipes
  kubejs/server_scripts/firmalife/recipes.js
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Bug

#790 add gt furnace recipe for wood ash
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#781 fixed rock knapping in field guide
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/getting_started/introduction.json
Labels: 1. Type: Bug

#779 Translate Uk
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/firmalife/irrigation.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/bloomery.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/crankshaft.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/fire_clay.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/glassworking.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/mechanical_power.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/papermaking.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/mechanics/pumps.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_ores/deep_sapphire.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_ores/deep_scheelite.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_ores/normal_saltpeter.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_tips/anvil_working_guide.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_tips/blast_furnace_tips.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_tips/faqs.json
  kubejs/assets/tfc/patchouli_books/field_guide/uk_ua/entries/tfg_tips/lv_machines.json
Labels: 1. Type: Translation

#768 create some raw coal recipes in coke oven and pyro oven
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#788 reduce recipe requirements for sticky resin in fluid solidifier
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#773 create sugar from beets in centrifuge
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#766 Remove buggy Pumpkin Chunks recipe
  kubejs/server_scripts/tfc/recipes.js
Labels: 1. Type: Enhancement

#882 Fixed the "look at water" task not working.
  config/ftbquests/quests/chapters/questsstoneage.snbt
  kubejs/assets/tfg/lang/en_us.json
  kubejs/server_scripts/ftb_quests/CustomQuests.js
  kubejs/server_scripts/tfg/events.js
Labels: 1. Type: Bug

#903 Increased Astikor Carts item size limit
  defaultconfigs/tfcastikorcarts-common.toml
Labels: 1. Type: Enhancement

#772 Add speed boost to nanosuit leggings
  kubejs/server_scripts/gregtech/armor.js
Labels: 1. Type: Feature

#908 Update small vessel capacity
  defaultconfigs/tfc-server.toml
Labels: 1. Type: Enhancement

#914 Universal circuits
  kubejs/assets/tfg/models/item/ev_universal_circuit.json
  kubejs/assets/tfg/models/item/hv_universal_circuit.json
  kubejs/assets/tfg/models/item/iv_universal_circuit.json
  kubejs/assets/tfg/models/item/luv_universal_circuit.json
  kubejs/assets/tfg/models/item/lv_universal_circuit.json
  kubejs/assets/tfg/models/item/mv_universal_circuit.json
  kubejs/assets/tfg/models/item/uhv_universal_circuit.json
  kubejs/assets/tfg/models/item/ulv_universal_circuit.json
  kubejs/assets/tfg/models/item/uv_universal_circuit.json
  kubejs/assets/tfg/models/item/zpm_universal_circuit.json
  kubejs/assets/tfg/textures/item/universal/ev_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/ev_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/hv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/hv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/iv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/iv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/luv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/luv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/lv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/lv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/mv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/mv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/uev_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/uev_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/uhv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/uhv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/uiv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/uiv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/ulv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/ulv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/uv_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/uv_universal_circuit.png.mcmeta
  kubejs/assets/tfg/textures/item/universal/zpm_universal_circuit.png
  kubejs/assets/tfg/textures/item/universal/zpm_universal_circuit.png.mcmeta
  kubejs/server_scripts/tfg/recipes.miscellaneous.js
  kubejs/server_scripts/tfg/tags.js
  kubejs/startup_scripts/gtceu/items.js
  kubejs/startup_scripts/tfg/constants.js
Labels: 1. Type: Feature

#915 Fix Curdled milk recipes to be the same as the barrel
  kubejs/server_scripts/tfc/recipes.machines.js
Labels: 1. Type: Bug, 2. Status: Accepted

#927 - Added recipes for combining and separating both fertilizers and hides.
  CHANGELOG.md
  kubejs/server_scripts/tfc/recipes.js
  kubejs/server_scripts/tfc/recipes.machines.js
Labels: 1. Type: Enhancement
