Repository TerraFirmaGreg-Team/Modpack-Modern, pull requests merged in 2025-01, with the labels that each got.

#663 precision mech in assembler
  kubejs/server_scripts/create/recipes.js
Labels: 4. Version 0.7.x

#667 Various fixes for 0.7.14
  kubejs/server_scripts/ae2/recipes.js
  kubejs/server_scripts/gregtech/recipes.js
  kubejs/startup_scripts/ae2/constants.js
Labels: 4. Version 0.7.x

#644 Fix stone dust tag
  kubejs/server_scripts/gregtech/tags.js
Labels: 4. Version 0.7.x

#686 Gas multiblocks
  kubejs/assets/gtceu/lang/en_us.json
  kubejs/assets/gtceu/lang/ru_ru.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/glassworking.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/faqs.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/infinite_resources.json
  kubejs/assets/tfg/models/block/artificial_end_portal_frame.json
  kubejs/client_scripts/tooltips.js
  kubejs/server_scripts/gregtech/recipes.js
  kubejs/server_scripts/minecraft/recipes.js
  kubejs/server_scripts/tfg/terrariums.js
  kubejs/startup_scripts/gtceu/machines.js
  kubejs/startup_scripts/gtceu/recipe_types.js
  kubejs/startup_scripts/main_server_script.js
  kubejs/startup_scripts/main_startup_script.js
  kubejs/startup_scripts/minecraft/constants.js
  kubejs/startup_scripts/tfg/blocks.js
  kubejs/startup_scripts/tfg/fluids.js
Labels: 1. Type: Feature

#690 Added ore index, started work on other TFC info category
  kubejs/assets/gtceu/lang/en_us.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/categories/tfg_tips.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_ores/index.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/faqs.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/infinite_resources.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/lv_machines.json
Labels: 1. Type: Feature

#698 Changed the AE2 network analyzer to HV instead of IV
  kubejs/server_scripts/ae2na/recipes.js
Labels: 1. Type: Enhancement

#703 Fix sprinklers + fix bread and yeast starter recipe conflict
  defaultconfigs/firmalife-server.toml
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/firmalife/irrigation.json
  kubejs/server_scripts/firmalife/recipes.js
  kubejs/server_scripts/tfc/recipes.js
  kubejs/startup_scripts/firmalife/constants.js
Labels: 1. Type: Bug

#704 Added recipes for create glass, more windows, fixed tinted glass recipe conflict
  kubejs/server_scripts/create/recipes.js
  kubejs/server_scripts/every_compat/recipes.js
  kubejs/server_scripts/every_compat/tags.js
  kubejs/server_scripts/main_server_script.js
  kubejs/server_scripts/minecraft/recipes.js
  kubejs/startup_scripts/create/constants.js
Labels: 1. Type: Feature

#705 Added missing recipe for nether brick
  kubejs/server_scripts/minecraft/recipes.js
  kubejs/startup_scripts/gtceu/constants.js
Labels: 1. Type: Feature

#707 Added armor trims
  kubejs/data/minecraft/tags/items/trim_materials.json
  kubejs/data/minecraft/trim_material/amethyst.json
  kubejs/data/minecraft/trim_material/bismuth.json
  kubejs/data/minecraft/trim_material/diamond.json
  kubejs/data/minecraft/trim_material/emerald.json
  kubejs/data/minecraft/trim_material/gold.json
  kubejs/data/minecraft/trim_material/lapis.json
  kubejs/data/minecraft/trim_material/lapis_lazuli.json
  kubejs/data/minecraft/trim_material/opal.json
  kubejs/data/minecraft/trim_material/pyrite.json
  kubejs/data/minecraft/trim_material/rose_gold.json
  kubejs/data/minecraft/trim_material/ruby.json
  kubejs/data/minecraft/trim_material/sapphire.json
  kubejs/data/minecraft/trim_material/silver.json
  kubejs/data/minecraft/trim_material/sterling_silver.json
  kubejs/data/minecraft/trim_material/topaz.json
  kubejs/server_scripts/create/tags.js
  kubejs/server_scripts/firmalife/tags.js
  kubejs/server_scripts/gregtech/tags.js
  kubejs/server_scripts/main_server_script.js
  kubejs/server_scripts/minecraft/recipes.js
  kubejs/server_scripts/tfcambiental/tags.js
  kubejs/startup_scripts/gtceu/constants.js
  kubejs/startup_scripts/minecraft/constants.js
Labels: 1. Type: Feature

#706 Add blast furnace tips entry
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/blast_furnace_tips.json
Labels: 1. Type: Enhancement

#712 Allows stick bundles to be used in the coke oven
  kubejs/server_scripts/tfc/tags.js
Labels: 1. Type: Feature

#713 Allows all colors of glass to be macerated/hammered to dust
  kubejs/server_scripts/create_connected/tags.js
  kubejs/server_scripts/gregtech/recipes.js
  kubejs/server_scripts/main_server_script.js
Labels: 1. Type: Feature

#724 Moved MV superconductor to early HV instead of late HV
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#702 Исправил опечатку в температуре кипения морской воды для рецепта маленькой кучки соли с 1000 на 100
  kubejs/server_scripts/tfc/recipes.js
Labels: 1. Type: Bug

#701 Add blaze burner, fix alternator
  kubejs/assets/create/models/block/blaze_burner/blaze_rods_large.obj
  kubejs/assets/create/models/block/blaze_burner/blaze_rods_small.obj
  kubejs/assets/create/textures/block/blaze_active.png
  kubejs/assets/create/textures/block/blaze_heater_brazier.png
  kubejs/assets/create/textures/block/blaze_idle.png
  kubejs/assets/create/textures/block/blaze_inert.png
  kubejs/assets/create/textures/block/blaze_super.png
  kubejs/assets/create/textures/block/blaze_super_active.png
  kubejs/client_scripts/tooltips.js
  kubejs/data/create/tags/items/blaze_burner_fuel/regular.json
  kubejs/data/create/tags/items/blaze_burner_fuel/special.json
  kubejs/server_scripts/create/recipes.js
  kubejs/server_scripts/create_additions/recipes.js
  kubejs/server_scripts/firmalife/recipes.js
  kubejs/server_scripts/gregtech/recipes.js
  kubejs/startup_scripts/create/constants.js
  kubejs/startup_scripts/create_additions/constants.js
  kubejs/startup_scripts/gtceu/items.js
  kubejs/startup_scripts/gtceu/machines.js
Labels: 1. Type: Feature

#643 Fix casing exploit, change recipes for tfc alloys
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Feature

#760 Add a Forging Guide to the Field Guide
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/anvil_working_guide.json
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/anvil_ui.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/anvil_ui_marked.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/perfectly_forged_item.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/steps.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/target_work_for_wrought_iron_pickaxe_head.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/work_bar_cheat_sheet.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/work_bar_numbers.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/wrought_iron_pickaxe_head_complete.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/wrought_iron_pickaxe_head_no_work.png
  kubejs/assets/tfg/textures/gui/field_guide/anvil_working_guide/wrought_iron_pickaxe_head_some_work.png
Labels: 1. Type: Enhancement

#759 Fixes wool cloth recipe conflict
  kubejs/server_scripts/tfc/recipes.js
Labels: 1. Type: Bug

#758 Get small dust from failed pressing
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#756 Fixed cassiterite heating "exploit"
  kubejs/server_scripts/tfc/recipes.js
  kubejs/startup_scripts/tfc/constants.js
Labels: 1. Type: Bug

#755 Tfc magma as passive boiler heater
  kubejs/server_scripts/tfc/tags.js
  kubejs/startup_scripts/tfc/constants.js
Labels: 1. Type: Enhancement

#753 Adds heat values for items with valid heating recipes but no heat values
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/blast_furnace_tips.json
  kubejs/server_scripts/tfc/data.js
Labels: 1. Type: Feature

#752 Add circuit settings to netherarium/enderarium
  kubejs/server_scripts/tfg/terrariums.js
  kubejs/startup_scripts/gtceu/recipe_types.js
Labels: 1. Type: Feature

#751 Fixed colored steel dust centrifuge recipes
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Bug

#750 Automatic Scraping with Sequenced Assembly
  kubejs/server_scripts/create/recipes.js
Labels: 1. Type: Feature

#745 Add glowstone as infinite lamp fuel
  kubejs/server_scripts/tfc/data.js
Labels: 1. Type: Feature

#744 Changed LV casing/hull recipes (again)
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Enhancement

#742 Add seaweed and kelp drying recipes
  kubejs/server_scripts/tfc/data.js
  kubejs/server_scripts/tfc/recipes.js
Labels: 1. Type: Feature

#740 Fix assembler wool recipe conflicts
  kubejs/server_scripts/minecraft/recipes.js
  kubejs/server_scripts/tfc/recipes.js
Labels: 1. Type: Bug

#739 Feature: Papermaking Overhaul with Wood
  config/ftbquests/quests/chapters/primitive_age.snbt
  kubejs/assets/gtceu/lang/en_us.json
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/papermaking.json
  kubejs/assets/tfg/lang/en_us.json
  kubejs/assets/tfg/textures/blocks/soaked_unrefined_paper.png
  kubejs/assets/tfg/textures/blocks/thermochemically_treated_hardwood_dust.png
  kubejs/assets/tfg/textures/item/hardwood_strip.png
  kubejs/assets/tfg/textures/item/soaked_hardwood_strip.png
  kubejs/assets/tfg/textures/item/soaked_unrefined_paper.png
  kubejs/server_scripts/gregtech/recipes.js
  kubejs/server_scripts/main_server_script.js
  kubejs/server_scripts/tfc/recipes.js
  kubejs/server_scripts/tfc/tags.js
  kubejs/server_scripts/tfg/recipes.js
  kubejs/server_scripts/tfg/tags.js
  kubejs/startup_scripts/main_startup_script.js
  kubejs/startup_scripts/tfc/constants.js
  kubejs/startup_scripts/tfg/items.js
  kubejs/startup_scripts/tfg/materials.js
Labels: 1. Type: Feature

#732 Hanging Sign Metal Dupe fix
  kubejs/server_scripts/gregtech/recipes.js
Labels: 1. Type: Bug

#737 Adjusted LV machines book entry
  kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/lv_machines.json
Labels: 1. Type: Bug

#733 Fix collapsible brick slab blocks
  kubejs/server_scripts/tfc/tags.js
  kubejs/startup_scripts/tfc/constants.js
Labels: 1. Type: Bug
